### ISSUE TITLE
Version >= 2.9.2 does not run on CentOS 7

### ISSUE THREAD

**Issue by craigwatson** [bitwarden/directory-connector#140]
All OS packages updated to latest as of 27th July 2021.

App errors:

```
pkg/prelude/bootstrap.js:1614
      throw error;
      ^

Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/1c37abc97553920fb7aad7712b63b174bcef21dabec7d18c818da9082e300aac/keytar.node)
    at tryImporting (pkg/prelude/bootstrap.js:1969:37)
    at tryImporting (pkg/prelude/bootstrap.js:2021:16)
    at process.dlopen (pkg/prelude/bootstrap.js:2044:7)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at Module.require (pkg/prelude/bootstrap.js:1593:31)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/snapshot/directory-connector/node_modules/keytar/lib/keytar.js:1:76)
```

**Comment by bclingan** [comment]
I also recently ran across this issue, are there any updates?
