### ISSUE TITLE
keytar.node: invalid ELF header (v2.9.4, linux)

### ISSUE THREAD

**Issue by zsturgess** [bitwarden/directory-connector#146]
v2.9.4 of the directory connector refuses to run with an `invalid ELF header` error. Tested in a `debian:stable` docker container.

```
$ docker run --rm -it debian:stable
<snip>
root@32956f7af2cf:~/bwdc# curl -Lo bwdc.zip 'https://github.com/bitwarden/directory-connector/releases/download/v2.9.3/bwdc-linux-2.9.3.zip'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   626  100   626    0     0   2259      0 --:--:-- --:--:-- --:--:--  2259
100 20.7M  100 20.7M    0     0  3903k      0  0:00:05  0:00:05 --:--:-- 4292k
root@32956f7af2cf:~/bwdc# unzip bwdc.zip && chmod u+x bwdc
Archive:  bwdc.zip
  inflating: bwdc                    
  inflating: keytar.node             
root@32956f7af2cf:~/bwdc# ./bwdc data-file
Could not find dir, "/root/.config/Bitwarden Directory Connector"; creating it instead.
Could not find data file, "/root/.config/Bitwarden Directory Connector/data.json"; creating it instead.
/root/.config/Bitwarden Directory Connector/data.json
root@32956f7af2cf:~/bwdc# rm bwdc && rm keytar.node 
root@32956f7af2cf:~/bwdc# curl -Lo bwdc.zip 'https://github.com/bitwarden/directory-connector/releases/download/v2.9.4/bwdc-linux-2.9.4.zip'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   626  100   626    0     0   1459      0 --:--:-- --:--:-- --:--:--  1455
100 20.9M  100 20.9M    0     0  3880k      0  0:00:05  0:00:05 --:--:-- 4455k
root@32956f7af2cf:~/bwdc# unzip bwdc.zip && chmod u+x bwdc
Archive:  bwdc.zip
  inflating: bwdc                    
  inflating: keytar.node             
root@32956f7af2cf:~/bwdc# ./bwdc data-file
pkg/prelude/bootstrap.js:1614
      throw error;
      ^

Error: /tmp/5238165e67d78604a6149268ccafb4fc3a4762ea41be38757c7472972f5efbd8/keytar.node: invalid ELF header
    at tryImporting (pkg/prelude/bootstrap.js:1969:37)
    at tryImporting (pkg/prelude/bootstrap.js:2021:16)
    at process.dlopen (pkg/prelude/bootstrap.js:2044:7)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at Module.require (pkg/prelude/bootstrap.js:1593:31)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/snapshot/directory-connector/node_modules/keytar/lib/keytar.js:1:76)
```

**Comment by eliykat** [comment]
Hi @zsturgess, thanks for the report. We've been able to reproduce this and we're looking into a fix. It looks like it may be a problem with the target in our build pipeline: https://support.contrastsecurity.com/hc/en-us/articles/360025177492-Invalid-ELF-Header. I recommend continuing to use the previous version as a workaround in the meantime.

**Comment by zsturgess** [comment]
@eliykat This is happening again with v2.9.7 - can we get this re-opened?

**Comment by eliykat** [comment]
Reopened and flagged with our devOps team for action.
