### ISSUE TITLE
Unable to run bwdc or AppImage

### ISSUE THREAD

**Issue by tam481** [bitwarden/directory-connector#19]
I extracted both bwdc and keytar.node into /usr/local/bin and made bwdc executable. However, when I run bwdc I get the following error:

pkg/prelude/bootstrap.js:1176
      throw error;
      ^

Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:729:18)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/snapshot/directory-connector/node_modules/keytar/lib/keytar.js:1:76)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)

How can I fix this?

**Comment by kspearrin** [comment]
Is libsecret installed on the machine?

**Comment by tam481** [comment]
Thanks. I installed libsecret by running `apt-get install libsecret-1-0` and that fixed it.

Might be worth adding that to the documentation :-)

**Comment by kspearrin** [comment]
I added it to the docs. Thanks.
