### ISSUE TITLE
bwdc sync failed

### ISSUE THREAD

**Issue by DGILLES-CPX** [bitwarden/directory-connector#264]
Hello team,
I have some trouble to sync with my AD. 
After configured bwdc  and test it using bwdc test with successfully response, I can't sync with this message. 

```
bwdc sync
/snapshot/directory-connector/build-cli/bwdc.js:19911
                error.message != null
                      ^

TypeError: Cannot read properties of null (reading 'message')
    at Function.error (/snapshot/directory-connector/build-cli/bwdc.js:19911:23)
    at SyncCommand.<anonymous> (/snapshot/directory-connector/build-cli/bwdc.js:21206:33)
    at Generator.throw (<anonymous>)
    at rejected (/snapshot/directory-connector/build-cli/bwdc.js:21184:65)
```

If you can help me on this issue, I will be happy.
thank you
Damien.

**Comment by eliykat** [comment]
Hi @DGILLES-CPX, what version are you using?

**Comment by DGILLES-CPX** [comment]
Hello,
The version is : 2.10.1 
Damien.

**Comment by YVLoub** [comment]
Hello, I am facing the same issue, when I run ```bwdc --pretty test``` i get bautiful json with data and everyting but when i switch to ```synch``` i get this error, here is the flow
```
2022-05-05T21:02:25.754553817Z You are logged in!                                                                       
2022-05-05T21:02:29.324050651Z Saved setting `ldap.password`.                                                           
2022-05-05T21:02:29.345889786Z Using synch: [sync]                                                                      
2022-05-05T21:02:33.096259464Z /snapshot/directory-connector/build-cli/bwdc.js:19911                                    
2022-05-05T21:02:33.096313045Z                 error.message != null                                                    
2022-05-05T21:02:33.096317716Z                       ^                                                                  
2022-05-05T21:02:33.096321156Z                                                                                          
2022-05-05T21:02:33.096324503Z TypeError: Cannot read properties of null (reading 'message')                            
2022-05-05T21:02:33.096328128Z     at Function.error (/snapshot/directory-connector/build-cli/bwdc.js:19911:23)         
2022-05-05T21:02:33.096331587Z     at SyncCommand.<anonymous> (/snapshot/directory-connector/build-cli/bwdc.js:21206:33)
2022-05-05T21:02:33.096338371Z     at Generator.throw (<anonymous>)                                                     
2022-05-05T21:02:33.096341923Z     at rejected (/snapshot/directory-connector/build-cli/bwdc.js:21184:65)               
2022-05-05T21:02:36.580866018Z You are not logged in.                                                                   
```
