### ISSUE TITLE
Unable to run bwdc

### ISSUE THREAD

**Issue by Github-Enjoyer** [bitwarden/directory-connector#283]
I extracted bwdc and keytar.node into /usr/local/bin and installed libsecret-1-0. However, when I run bwdc I get the following error:

pkg/prelude/bootstrap.js:1833
      throw error;
      ^

Error: /tmp/pkg/0700016bcd/keytar/build/Release/keytar.node: failed to map segment from shared object
    at process.dlopen (pkg/prelude/bootstrap.js:2212:28)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1187:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1812:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/directory-connector/node_modules/keytar/lib/keytar.js:1:76)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) {
  code: 'ERR_DLOPEN_FAILED'
}

Any idea on how I can fix this?

**Comment by dbosompem** [comment]
Hi @Github-Enjoyer, thanks for reporting this. However we use GitHub issues as a place to track bugs and other development related issues. Your issue appears to be a support request, or would otherwise be better handled by our dedicated Customer Success team.

Please contact us using our [Contact page](https://bitwarden.com/contact). You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed for now.

**Comment by dbosompem** [comment]
Hi @Github-Enjoyer thanks for reporting this issue. This issue appears to be a support request, or would otherwise be better handled by our dedicated Customer Success team. 

Please contact us using our [Contact Page](https://bitwarden.com/contact). You can include a link to this issue in the message content.

I'll close this now, but please comment after you have tried suggested solutions and still facing challenges.
