### ISSUE TITLE
Sync Error from Azure AD -An unhandled server error has occurred

### ISSUE THREAD

**Issue by mrventerj** [bitwarden/directory-connector#96]
Does anyone have an idea what this means? It's not a seat limit.

Failed to load resource: the server responded with a status of 500 ()
vendor.js:4615 ERROR Error: Uncaught (in promise): errorResponse_ErrorResponse: {"response":{"Object":"error","Message":"An unhandled server error has occurred.","ValidationErrors":null,"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null},"message":"An unhandled server error has occurred.","validationErrors":null,"statusCode":500}
    at resolvePromise (vendor.js:349507)
    at vendor.js:349414
    at rejected (utils.ts:100)
    at ZoneDelegate.push.ZoneDelegate.invoke (vendor.js:349061)
    at Object.onInvoke (vendor.js:28632)
    at ZoneDelegate.push.ZoneDelegate.invoke (vendor.js:349060)
    at Zone.push.Zone.run (vendor.js:348818)
    at vendor.js:349566
    at ZoneDelegate.push.ZoneDelegate.invokeTask (vendor.js:349096)
    at Object.onInvokeTask (vendor.js:28620)

**Comment by mrventerj** [comment]
@kspearrin Sorry for the @  - do you know what the error above indicates?

I have tried a new  Azure apps registration alongside running the connector on a different server - with the same error.

**Comment by kspearrin** [comment]
It's a server error. Are you self-hosting? You should check your server logs for the error.

**Comment by mrventerj** [comment]
@kspearrin  Thanks for the reply - yes I am self-hosting - could you point me to which directory  I should be looking at for the logs ?

**Comment by kspearrin** [comment]
./bwdata/logs/Api

**Comment by mrventerj** [comment]
This is the error I get when I try "Start Sync"\"Sync Now"

How do I identify which key is the problem?

`[Error] An item with the same key has already been added. Key: f8941cf2-a4a9-448d-a540-ada39267b015
System.ArgumentException: An item with the same key has already been added. Key: f8941cf2-a4a9-448d-a540-ada39267b015
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Bit.Core.Services.OrganizationService.ImportAsync(Guid organizationId, Nullable`1 importingUserId, IEnumerable`1 groups, IEnumerable`1 newUsers, IEn$
   at Bit.Api.Controllers.OrganizationsController.Import(String id, ImportOrganizationUsersRequestModel model) in /home/runner/work/server/server/src/Api/$
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor ex$
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`$
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task l$
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTa$
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, Stat$
`

**Comment by Greenderella** [comment]
[Error] An item with the same key has already been added. Key: f8941cf2-a4a9-448d-a540-ada39267b015 System.ArgumentException: An item with the same key has already been added.

Make sure you remove any duplicates (users and/or groups), as this will always fail in this event.
